services:
  - type: web
    name: yelp-survey
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_DISK_PATH
        value: /opt/render/project/persistent-data
    disk:
      name: survey-data
      mountPath: /opt/render/project/persistent-data
      sizeGB: 1